### ISSUE TITLE
Error on training

### ISSUE THREAD

**Issue by mahfujur1** [lulujianjie/efficient-person-generation-for-reid#1]
Hi Lulujianjie,

I was trying to train the code. After generating the heatmaps (pose and part), I run train.py file and for the error.
`FileNotFoundError: [Errno 2] No such file or directory: './part/train.npy'
`
It seems that we need a train.npy file.. Can you please help me to sort out this issue? Thanks in advance.

**Comment by lulujianjie** [comment]
> Hi Lulujianjie,
> 
> I was trying to train the code. After generating the heatmaps (pose and part), I run train.py file and for the error.
> `FileNotFoundError: [Errno 2] No such file or directory: './part/train.npy' `
> It seems that we need a train.npy file.. Can you please help me to sort out this issue? Thanks in advance.

Hi, You need to change 'restore=true' to 'false', at line 24 and line 29 of 'data-generation-GAN/datasets/make_dataloader.py'
The npy file needs to be generated first. Since this process is time-consuming, you can directly load the generated npy file after you generate it.

**Comment by mahfujur1** [comment]
Hi Lulujianjie, 
Thank you for your answer. May I get your paper link?
